from typing import Callable, Optional, Tuple

NFQNL_COPY_NONE: int
NFQNL_COPY_META: int
NFQNL_COPY_PACKET: int

NFQA_CFG_F_FAIL_OPEN: int
NFQA_CFG_F_CONNTRACK: int
NFQA_CFG_F_GSO: int

NF_DROP: int
NF_ACCEPT: int
NF_STOLEN: int
NF_QUEUE: int
NF_REPEAT: int
NF_STOP: int

class NetfilterQueueData:
    """Wrapper for (struct nfq_data *)."""

    def get_packet_hw(self) -> Optional[str]: ...
    def get_nfmark(self) -> int: ...
    def get_timestamp(self) -> Tuple[int, int]: ...
    def get_indev(self) -> int: ...
    def get_physindev(self) -> int: ...
    def get_outdev(self) -> int: ...
    def get_physoutdev(self) -> int: ...
    def get_payload(self) -> str: ...
    def get_uid(self) -> int: ...
    def get_gid(self) -> int: ...
    def set_verdict(self, verdict: int, mark: Optional[int] = None) -> None: ...

class NetfilterQueueQueueHandle:
    """Wrapper for (struct nfq_q_handle *)."""

    def set_mode(self, mode: int, range: int) -> None: ...
    def set_flags(self, mask: int, flags: int) -> None: ...
    def set_maxlen(self, queuelen: int) -> None: ...
    def destroy(self) -> None: ...

class NetfilterQueueHandle:
    """Wrapper for (struct nfq_handle *)."""

    def bind_pf(self, pf: int) -> None: ...
    def unbind_pf(self, pf: int) -> None: ...
    def create_queue(self, num: int, callback: Callable[[NetfilterQueueData], object]) -> NetfilterQueueQueueHandle: ...
    def handle_packet(self, data: str) -> None: ...
    def fd(self) -> int: ...
    def close(self) -> None: ...

def open() -> NetfilterQueueHandle: ...
